### ISSUE TITLE
opentracing-redis-spring-data2 doesn't support health check

### ISSUE THREAD

**Issue by huangxfchn** [opentracing-contrib/java-redis-client#49]
# description
* spring boot 2.1.3, opentracing-redis-spring-data2 0.1.2
* when spring actuate redis do health check, then trigger `Redis health check failed java.lang.IllegalArgumentException`

# the reason
`io.opentracing.contrib.redis.spring.data2.connection.TracingRedisConnectionFactory#getConnection()` does not determine if it is `RedisClusterConnection`, and `org.springframework.data.redis.connection.jedis.JedisConnectionFactory#getConnection()` Will return `RedisClusterConnection`, but `TracingRedisConnectionFactory` will still be wrapped into a non-clustered `RedisConnection`

When spring actuate does a health check on redis, it will determine whether it is a `RedisClusterConnection`, `org.springframework.boot.actuate.redis.RedisHealthIndicator#doHealthCheck` key code is as follows, will be mistaken for non-clustered links.
```
if (connection instanceof RedisClusterConnection) {
	ClusterInfo clusterInfo = ((RedisClusterConnection) connection).clusterGetClusterInfo();
	builder.up().withDetail("cluster_size", clusterInfo.getClusterSize())
			.withDetail("slots_up", clusterInfo.getSlotsOk())
			.withDetail("slots_fail", clusterInfo.getSlotsFail());
}
else {
	Properties info = connection.info();
	builder.up().withDetail(VERSION, info.getProperty(REDIS_VERSION));
}
```

# the solution
Modify the `TracingRedisConnectionFactory` code to increase the judgment of `RedisClusterConnection`
```
@Override
public RedisConnection getConnection() {
    RedisConnection connection = this.connectionFactory.getConnection();
    if ( connection instanceof RedisClusterConnection) {
        return new TracingRedisClusterConnection((RedisClusterConnection)connection, tracingConfiguration);
    }
    return new TracingRedisConnection(connection, tracingConfiguration);
}

@Override
public ReactiveRedisConnection getReactiveConnection() {
    if (connectionFactory instanceof ReactiveRedisConnectionFactory) {
        ReactiveRedisConnection connection = ((ReactiveRedisConnectionFactory) connectionFactory).getReactiveConnection();
        if ( connection instanceof ReactiveRedisClusterConnection) {
            return new TracingReactiveRedisClusterConnection((ReactiveRedisClusterConnection)connection, tracingConfiguration);
        }
        return new TracingReactiveRedisConnection(((ReactiveRedisConnectionFactory) connectionFactory).getReactiveConnection(), tracingConfiguration);
    }
    return null;
}
```

# exception stacktrace
```
Redis health check failed java.lang.IllegalArgumentException: Value must not be null
	at org.springframework.util.Assert.notNull(Assert.java:198)
	at org.springframework.boot.actuate.health.Health$Builder.withDetail(Health.java:228)
	at org.springframework.boot.actuate.redis.RedisHealthIndicator.doHealthCheck(RedisHealthIndicator.java:67)
	at org.springframework.boot.actuate.health.AbstractHealthIndicator.health(AbstractHealthIndicator.java:84)
	at org.springframework.boot.actuate.health.CompositeHealthIndicator.health(CompositeHealthIndicator.java:98)
	at org.springframework.boot.actuate.health.HealthEndpoint.health(HealthEndpoint.java:50)
	at org.springframework.boot.actuate.health.HealthEndpointWebExtension.health(HealthEndpointWebExtension.java:54)
```

**Comment by malafeev** [comment]
PR merged
