### ISSUE TITLE
TracingRedisConnection not working with Spring-Boot 2.5.x

### ISSUE THREAD

**Issue by dreis2211** [opentracing-contrib/java-redis-client#60]
Hi,

after upgrading a project to Spring-Boot 2.5.x we get errors like the following:
```
java.lang.AbstractMethodError: Receiver class io.opentracing.contrib.redis.spring.data2.connection.TracingRedisConnection does not define or inherit an implementation of the resolved method 'java.lang.Boolean zAdd(byte[], double, byte[], org.springframework.data.redis.connection.RedisZSetCommands$ZAddArgs)' of interface org.springframework.data.redis.connection.RedisConnection.
	at org.springframework.data.redis.connection.DefaultStringRedisConnection.zAdd(DefaultStringRedisConnection.java:1338)
	at org.springframework.data.redis.connection.RedisZSetCommands.zAdd(RedisZSetCommands.java:569)
	at org.springframework.data.redis.core.DefaultZSetOperations.lambda$add$0(DefaultZSetOperations.java:56)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:222)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:189)
	at org.springframework.data.redis.core.AbstractOperations.execute(AbstractOperations.java:96)
	at org.springframework.data.redis.core.DefaultZSetOperations.add(DefaultZSetOperations.java:56)
```

It seems this project is not really up-to-date anymore given that it's on Spring-Boot 2.2.x. Is there any alternative project that we could go for?

Cheers,
Christoph

**Comment by lavanya2290** [comment]
Any update on this.
